from ultralytics import YOLO

# Call form the Object Detection.py
def load_train_the_model(epoch):

    # Imports the YOLO(You Look Only Once) version 8 nano pretrained model
    # It is train on bases of 80 classes on the object detection
    model = YOLO("yolov8n.pt")

    # We are retraining the model on the classes we needed  
    model.train(
        data="data.yaml", # It is automatically generated by the annotation.py
        epochs=epoch, # The user entered
        imgsz=640, # size of the image should be after converting  
        project="trained_model",  # main folder name
        name="custom_model",  # Sub folder which has weighs and the trained information   
        exist_ok=True         
    )
    
    # Make an object 
    custom_model = YOLO("trained_model/custom_model/weights/best.pt")

    # Return the pretrained model 
    return custom_model